### ISSUE TITLE
Problem with pmta-config

### ISSUE THREAD

**Issue by Colls** [magicdude4eva/port25-bouncehandler#1]
Hello. Manual bounce-processing works perfectly but I have an error 
`
Error activating configuration: Error running " /usr/bin/php /opt/pmta/bouncehandler/bouncehandler.php": not executable
`
while trying to add this to my pmta-config
`
<acct-file | /usr/bin/php /opt/pmta/bouncehandler/bouncehandler.php>
    records b
    record-fields b timeQueued,bounceCat,vmta,orig,rcpt,srcMta,dlvSourceIp,jobId,dsnStatus,dsnMta,dsnDiag
</acct-file>
`
Can you help with that?
(permissions of bouncehandler-folder 755 root root, also tried 755 pmta pmta)

**Comment by magicdude4eva** [comment]
Hi there,

ensure that the folder with the scripts have the correct ownership and execute permissions:
```
chown -R pmta:pmta /opt/pmta/bouncehandler/
chmod a+x /opt/pmta/bouncehandler/bouncehandler.php
```

Since Port25 runs as user "pmta" the bouncehandler folder needs to have the same ownership. I hope that helps.

**Comment by Colls** [comment]
The problem wasn't in permissions. It was in unnessessary space in pmta-config after "|"
`<acct-file | /usr/bin/php /opt/pmta/bouncehandler/bouncehandler.php>` - leads to error described above
`<acct-file |/usr/bin/php /opt/pmta/bouncehandler/bouncehandler.php>` - right choice :)

**Comment by magicdude4eva** [comment]
Tks - I fixed the typo in the README
