### ISSUE TITLE
PowerMTA bounce handler MailWizz not Working

### ISSUE THREAD

**Issue by GitHub2041** [magicdude4eva/port25-bouncehandler#13]
@magicdude4eva  any solution ?

PowerMTA bounce handler MailWizz not working . there is error powemta log 

When i am run this command 

**cat /var/log/pmta/bounce-2017-09-04-0000.csv | /usr/bin/php /opt/pmta/bouncehandler/bouncehandler.php --debug**

/var/log/pmta/log

2017-09-04 16:17:04 Unable to parse serial number: number missing
2017-09-04 16:17:08 Unable to parse serial number: number missing
2017-09-04 16:17:14 Unable to parse serial number: number missing
2017-09-04 16:17:18 Unable to parse serial number: number missing
2017-09-04 16:17:23 Unable to parse serial number: number missing
2017-09-04 16:17:26 Unable to parse serial number: number missing

**Comment by masharif46** [comment]
Hey ! @GitHub2041  I think Problem with Configuration PowerMTA bounce handler & MailWizz , Ensure PHP 5.6 or Latest ,  You can following this [Port25 bounce- and FBL processor for MailWizz](https://github.com/magicdude4eva/port25-bouncehandler/releases/tag/1.3)   Remember You must add  Additional Headers .// MailWizz via "Servers -> Delivery Servers: Additional Headers"  it's look like

![](https://raw.githubusercontent.com/magicdude4eva/port25-bouncehandler/master/mailwizz-x-job-header-for-port25.png)


**Port25 bounce- and FBL processor for MailWizz and Interspire**

I am Test with PowerMTA 4.5r8 & PowerMTA 4.5r10 (software is properly licensed), PowerMTA bounce handler MailWizz Work fine.

This is my MailWizz Dashboard Work Perfect  
 

![](https://user-images.githubusercontent.com/13065284/29994763-f62e733c-8ff8-11e7-859b-d3cb0510facf.jpg)

if you failure to configure. contact with i will try to help  you,  Skype : masharfi46

Thanks again Both Bro,  Both r helpful  @magicdude4eva  @twisted1919

**Comment by GitHub2041** [comment]
THANK YOU ! @masharif46  EXCELLENT KNOWLEDGE & EXCELLENT SUPPORT. ALSO THANK YOU @magicdude4eva  FOR EXCELLENT SCRIPT
