### ISSUE TITLE
Unsubscribe several domains 

### ISSUE THREAD

**Issue by Nelex** [magicdude4eva/port25-bouncehandler#18]
Hi Gerd, thanks for great contritubion to Mailwizz love it, I'm having an issue with Unsubscribe extension. We have several domains and in current configuration it's only possible to specify one FBL domain, is there an easy workaround for this?

**Comment by magicdude4eva** [comment]
Hi @Nelex, you could ask Twisted from MailWizz to perhaps expand on it.

Another option is that you use just on "catch-all-domain" which then relays the unsubscribe email to the relevant server. That should be fairly simple to configure within Port25.

**Comment by Nelex** [comment]
HI Gerd,

Thanks for fast reply, I just did and he told me that -  I don't know how the above plugin works, but i do know mailwizz adds the proper List-unsubscribe header with proper info. 

Am I missing something or you created it when it was working badly in mailwizz?

Great idea on catch all btw

**Comment by magicdude4eva** [comment]
Hi,

it was probably a year ago where I asked Twisted on how I could have a List-Unsubscribe header and he was kind enough to write an extension for me which is available here: https://github.com/magicdude4eva/port25-bouncehandler/tree/master/mailwizz-unsubscribe-extension

I can barely code myself out of a paper-bag with PHP (Java is really my strength) so I would struggle making that extension work for multiple domains.

If the catch-all does not work (I would make the domain just very generic), ask him if he would consider adding the List-Unsubscribe as a generic feature. It should not take much effort to do - he is super fast. 

As far as I remember the only change I had to make was getting the header in the right format - i.e. here: https://github.com/magicdude4eva/port25-bouncehandler/blob/master/mailwizz-unsubscribe-extension/ListUnsubscribeExt.php#L143

**Comment by Nelex** [comment]
Gerb, 

Paper-bag out ROFL, yeah I just spoke to him, he said that mailwizz adds the proper List-unsubscribe header with proper info. 
It's just gmail will show it only if you have a good reputation.

Anything your extension adds on top of this?

**Comment by magicdude4eva** [comment]
I am still on 1.4.3. Is his "List-Unsubscribe" a recent change? If so, could you perhaps have a look at how his List-Unsubscribe header looks like in the email.

I would especially be interested in what the domain would be like - i.e. can you customise the sub-domain? If it only allows a top-level domain, this might be problematic for some users, as most use Port25 for example as online outbound MTA.

For reference - this is one of our recent mails:
```
List-Unsubscribe: <mailto:la995kzmdb87d.bj119oa4rw7cc.qg561p948q3f9@fbl-unsub.THEDOMAIN.COM?subject=unsubscribe>,
 <http://MAILWIZZ.COM/lists/bj119oa4rw7cc/unsubscribe/la995kzmdb87d/qg561p948q3f9/unsubscribe-direct?source=email-client-unsubscribe-button>
```

**Comment by magicdude4eva** [comment]
Closing this - I upgraded MailWizz to 1.5.7 over the weekend and the current List-Unsubscribe handling still works - proof:
```
[26/Jun/2018 17:41:22] Port25 PowerMTA unsubscribe-handler
[26/Jun/2018 17:41:22] (C) 2016-2017 Gerd Naschenweng  https://github.com/magicdude4eva
[26/Jun/2018 17:41:22] ------------------------------------------------------------------
[26/Jun/2018 17:41:22] Bounce-provider: MailWizz, initialising
[26/Jun/2018 17:41:22]    Endpoint-URL=[REDACTED]]
[26/Jun/2018 17:41:22]    MailWizz enabled!
[26/Jun/2018 17:41:22] Bounce-provider: MailWizz, complete
[26/Jun/2018 17:41:22] Initialising RRD reporting via /var/log/pmta/pmta.rrd
[26/Jun/2018 17:41:22]  Received:
---------------------------------------------
Return-Path: [REDACTED]]
<SNIP - REDACTED>
Date: Tue, 26 Jun 2018 08:41:18 -0700
Subject: unsubscribe
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 7bit
Content-Disposition: inline

This message was automatically generated by Gmail.

---------------------------------------------
[26/Jun/2018 17:41:22] * Unsubscribe request from [REDACTED]] for [REDACTED]].[REDACTED]].[REDACTED]]@fbl-unsub.[REDACTED]]
[26/Jun/2018 17:41:22]    - success for listUID=[REDACTED]]
[26/Jun/2018 17:41:22] * Done processing
```
