### ISSUE TITLE
Bounces not shown in MailWizz

### ISSUE THREAD

**Issue by marioderksen** [magicdude4eva/port25-bouncehandler#21]
Hi Gerd (magicdude4eva)!

First.. a big thank you for putting this code online.
But I have an issue and I can't seem to figure out what the problem is.

I read the documentation multiple times but I get stuck.
When I set things up like you discibed in the readme file, and run a campaign with 2 good and 2 fake mailaddresses, I don't see the bounces in my MailWizz campaign report.
The 2 fake mailaddresses get unsubscribed, so that part looks allright, although I wander why you decide to set these bounce addresses to UNSUBSCRIBE in stead of BOUNCED/BLACKLISTED like MailWizz does.

Also there is a contradictionary in your README.md and the bouncehandler.php:
README.md says:
`<acct-file |/usr/bin/php /opt/pmta/bouncehandler/bouncehandler.php>`
 `records b`
`record-fields b timeQueued,bounceCat,vmta,orig,rcpt,srcMta,dlvSourceIp,jobId,dsnStatus,dsnMta,dsnDiag`
`</acct-file>`

bouncehandler.php * Notes says:
`<acct-file | /usr/bin/php /opt/pmta/bouncehandler/bouncehandler.php>`
`records b`
`type,timeQueued,bounceCat,vmta,orig,rcpt,srcMta,dlvSourceIp,jobId,dsnStatus,dsnMta,dsnDiag`
`</acct-file>`

Restarting the pmta when the version of bouncehandler.php * Note gives me a Parse error in line 44 of /etc/pmta/config: unknown directive. So this is defenitly incorrect (don't schoot the messenger)!

It would also be handy if you can tell me which MailWizz crons can be commented out listed below:
`#3 Bounce handler, runs once at 10 minutes.`
`*/10 * * * * /usr/bin/php -q /var/www/smtp1.mailhouserock.com/public_html/mailer/apps/console/console.php bounce-handler >/dev/null 2>&1`
`#4 Feedback loop handler, runs once at 20 minutes.`
`*/20 * * * * /usr/bin/php -q /var/www/smtp1.mailhouserock.com/public_html/mailer/apps/console/console.php feedback-loop-handler >/dev/null 2>&1`
`#5 Delivery/Bounce processor, runs once at 3 minutes.`
`*/3 * * * * /usr/bin/php -q /var/www/smtp1.mailhouserock.com/public_html/mailer/apps/console/console.php process-delivery-and-bounce-log >/dev/null 2>&1`

Commenting out #3 and #4 is obvious to me but what about #5?

Cheers!

**Comment by masharif46** [comment]
check Powermta Log files.

**Comment by marioderksen** [comment]
Hi masharif46,

Thanks for the reply...
This is (one of the four bounces) I see in the log for the last sent test campaign:
`[07/Jan/2018 08:50:03] Bounce: bad-domain from=bounce@example.com via pmta-vmta4/feger@mdfsdfsdsdck.com jobId=, dsnStatus=5.1.2 (bad destination system: no such domain)
[07/Jan/2018 08:50:03]    MailWizz: unsubscribe for feger@mdfsdfsdsdck.com:
[07/Jan/2018 08:50:04]    - success: MAILLIST1`

In my report I see Bounces 0%
Hard bounces 0
Hard bounces rate 0%
Soft bounces 0
Soft bounces rate 0%

**Comment by neeksor** [comment]
https://github.com/magicdude4eva/port25-bouncehandler/blob/master/setup.php#L44

bad-domain is in bounceCategories.
As for why it wasn't counted, I don't know.

**Comment by marioderksen** [comment]
I figured it out. At least I think I did.

**Q1** - magicdude4eva, can you confirm this application only runs if you use the API key for one particular customer?

I made a customer (myself to protect the API keys), but these keys do not work as it seems.
**Q2** - Can you make it work for multiple customers by using some code like this, see below?

`$customers = Customer::model()->findAllByAttributes(['status' => 'active']);
foreach ($customers as $customer) {
     $apiKey = CustomerApiKey::model()->findByAttributes(['customer' => $customer->customer_id]);
     if (empty($apiKey)) {
        $apiKey = new CustomerApiKey();
        $apiKey->customer_id = $customer->customer_id;
        $apiKey->save();
     }
     $publicKey = $apiKey->public_key;
     $privateKey = $apiKey->private_key;
}`

**Comment by masharif46** [comment]
@marioderksen   follow installation documentation. it's work fine with PowerMTA 4.5r8  &  Mailwizz - 1.4.3. i think some problem with installation . it's working file without any Problem . NOTE : PowerMTA Must valid license .

**Comment by marioderksen** [comment]
Hi masharif46,

Thanks for the reply.
I can recall It works.... only not with keys from another user.
This is what I needed so I had to find my own solution.

I wrote a script myself.
Now it works like a sunshine :)

Regards, Mario
