### ISSUE TITLE
PHP Warning:  fgetcsv() expects parameter 1 to be resource

### ISSUE THREAD

**Issue by davidusany** [magicdude4eva/port25-bouncehandler#28]
Dear @magicdude4eva & other users,

I'm getting the following error in logs:

> PHP Warning:  fgetcsv() expects parameter 1 to be resource, string given in /opt/pmta/bouncehandler2/bouncehandler.php on line 124

Looking for help!

Thanks

**Comment by magicdude4eva** [comment]
Please provide detailed error log. I also suggest to fully read: https://github.com/magicdude4eva/port25-bouncehandler/blob/master/README.md
