### ISSUE TITLE
Mailwizz version -1.8.3  ALL Bounce Mark As Unsubscribed

### ISSUE THREAD

**Issue by masharif46** [magicdude4eva/port25-bouncehandler#31]
Now 2019 ! Mailwizz version - 2 Coming Soon !   Mailwizz version Running -1.8.3.   Port25 PowerMTA bounce handler . Port25 feedback loop processing Work fine. ALL Bounce Mark As Unsubscribed . Any Possibility to Fixed This issues @magicdude4eva @twisted1919

**Comment by magicdude4eva** [comment]
Unfortunately I am not able to support this project anymore. I have am currently not using Mailwizz or Port25. Please fork the project.
