### ISSUE TITLE
PHP Error

### ISSUE THREAD

**Issue by wgalafassijr** [magicdude4eva/port25-bouncehandler#7]
Hi,

I have this error: 
cat /var/log/pmta/bounce-2017-03-24-0000.csv | /usr/bin/php bouncehandler.php 
PHP Parse error:  syntax error, unexpected '[' in /opt/pmta/bouncehandler/providers/bounce-provider-interspire.php on line 37

**Comment by magicdude4eva** [comment]
Can you check what is on line #37 - it perhaps the file is wrong - see here: https://github.com/magicdude4eva/port25-bouncehandler/blob/master/providers/bounce-provider-interspire.php#L37

**Comment by wgalafassijr** [comment]
Hi,
Thanks for the the help.

Yes i have the same on my line #37 http://prntscr.com/ep0fsl

**Comment by wgalafassijr** [comment]
Some idea?

**Comment by magicdude4eva** [comment]
Can you download the master zip and see if that works: https://github.com/magicdude4eva/port25-bouncehandler/archive/master.zip

**Comment by wgalafassijr** [comment]
Same error: 

cat /var/log/pmta/bounce-2017-03-24-0000.csv |  php bouncehandler.php     
PHP Parse error:  syntax error, unexpected '[' in /opt/pmta/bouncehandler/providers/bounce-provider-interspire.php on line 37

On line 37 i have: $apiInterspireListIDs = [];

**Comment by wgalafassijr** [comment]
Any other tip?

**Comment by lakkisinghal** [comment]
Hi,
Looks like you are running PHP version < 5.4. This [] works on  >=5.4 version. 
You can replace this '[]' with 'array()'. 
Hope this will work.

**Comment by magicdude4eva** [comment]
Thanks @lakkisinghal if this works. On our environment we are running PHP7. Anything below PHP5.6 should really be considered outdated - i.e. <5.4 will not receive any updates/fixes and support ended July 2016.

**Comment by wgalafassijr** [comment]
Updating php version solved the issue. Thanks for all.
