### ISSUE TITLE
email not triggered

### ISSUE THREAD

**Issue by wgalafassijr** [magicdude4eva/port25-bouncehandler#8]
Hi,

This kind of error are not begin "detected". Some idea?

b,2017-05-04 18:07:21-0300,2017-05-04 18:07:17-0300,sender@galafassi.org,3amygos@terra.com.br,,failed,5.1.1 (bad destination mailbox address),smtp;550 5.1.1 5.1.1 <3amygos@terra.com.br>: Recipient address rejected,vip-us-br-mx.terra.com (208.84.244.133),policy-related,smtp,galafassi.org (127.0.0.1),smtp,66.45.248.227,208.84.244.133,"ENHANCEDSTATUSCODES,8BITMIME,SIZE,AUTH,STARTTLS,AUTH:PLAIN,AUTH:CRAM-MD5,AUTH:LOGIN",,pmta-vmta6,,,terra.com.br/pmta-vmta6,pmta-pool,<949d23925de955ec12375ea862224e64@galafassi.org>,"""Admin"" <sender@galafassi.org>",sender@galafassi.org

Thanks,
Wilson

**Comment by magicdude4eva** [comment]
Yes, have a look at https://github.com/magicdude4eva/port25-bouncehandler/blob/master/setup.php#L44 and then adjust your setup.php and add the bounce-category "policy-related" to the list of bounce categories.

**Comment by wgalafassijr** [comment]
very thanks.
