### ISSUE TITLE
Invalid API request signature For Mailwizz 1.3.8.6

### ISSUE THREAD

**Issue by shuvoaftab** [magicdude4eva/port25-bouncehandler#9]
[10/Jul/2017 16:57:25] Bounce: bad-mailbox from=bounce@b.domain.info via smtp4/preethiiyersadasdsadsa773@gdmail.com
MailWizzApi_Params Object
(
    [_data:MailWizzApi_Params:private] => Array
        (
            [status] => error
            [error] => Invalid API request signature. Please refer to the documentation.
        )

    [_readOnly:MailWizzApi_Params:private] =>
)

**Comment by magicdude4eva** [comment]
Check that you have set "DISABLE SIGNATURE CHECK" to "YES" in Settings->API -
 direct URL: https://YOURMAILWIZZ.SERVER/backend/settings/api

**Comment by shuvoaftab** [comment]
But in Version 1.3.8.6 There's No option to do that. 
Can i do it in that version?

**Comment by magicdude4eva** [comment]
I think I know what happened. When you followed my instructions [here](https://github.com/magicdude4eva/port25-bouncehandler/tree/master/providers/MailWizzApi) you would have downloaded an API SDK which was updated to a version of MailWizz after 1.3.8.6 and your install of MailWizz 1.3.8.6 is incompatible with the MailWizz API which supports API signature checks.

You could either ask Twisted1919 on his [forum](https://forum.mailwizz.com/forums/announcements/) but I think a better option would be to upgrade to the most current version of MailWizz (1.4.3)

**Comment by shuvoaftab** [comment]
I just upgraded to 1.4.3 and tested according to your Guidelines.
It worked Now :)
but the emails Unsubscribed in Lists and don't show up in Campaign Stats.
also is there any way to get them in campaign Bounce section?

**Comment by magicdude4eva** [comment]
This is great to know. With regards to campaign API/bounce-handling, I did have a similar request and this was not possible back then - https://github.com/magicdude4eva/port25-bouncehandler/issues/4. If the API nowadays supports it, it would be easy to just do a pull request and then make the changes in the MailWizz bounce-handler.

**Comment by shuvoaftab** [comment]
So should i ask twisted1919 ? for this if he can help us?

**Comment by magicdude4eva** [comment]
The bounce-handling is done in https://github.com/magicdude4eva/port25-bouncehandler/blob/master/providers/feedback-loop-processor.php#L75 which then calls https://github.com/magicdude4eva/port25-bouncehandler/blob/master/providers/bounce-provider-mailwizz.php#L75

Based on our legislation we unsubscribe a recipient from all mailing lists in the system when a bounce happens. I know that some people have more "liberal" views on this. 

When I initially provided this functionality, I hoped that MailWizz function `$MailWizzEndPoint->unsubscribe($subscription['list']['list_uid'], $subscription['subscriber_uid']);` had some option to provide a "bounce-code/flag" but that did not exist. Maybe it does now. It should be fairly simple to adjust the provided code though if you need to. (Or get someone to contribute - I am at the moment stretched with my day job and will be on leave for several weeks in August as well).
